repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/crate-ci/typos
    rev: v1.14.3
    hooks:
      - id: typos
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
# -   repo: https://github.com/hadolint/hadolint
#     rev: v2.10.0
#     hooks:
#       - id: hadolint
