name: osgood CI suite

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install Pre-Commit dependencies
      run: pip install scspell3k
    - uses: pre-commit/action@v3.0.0
  run-integration-test:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Install osgood
        run: pip install -e . && pytest
