name: osgood CI suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Writes changes in the local checkout
        uses: crate-ci/typos@master
        with:
          write_changes: true
      - name: Lint with ruff
        run: |
          ruff .
      - name: mypy it
        run: |
          mypy .
      - name: Install package
        run: pip install -e .
      - name: Run pytest
        run: pytest
