name: osgood CI suite

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v2
      - name: Check spelling
        uses: crate-ci/typos@master
      - name: Writes changes in the local checkout
        uses: crate-ci/typos@master
        with:
          write_changes: true
      - name: Lint with ruff
        run: |
          # stop the build if there are linting issues
          ruff .

  run-tests:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install package
      run: pip install -e .
    - name: Install pytest
      run: pip install pytest
    - name: Run pytest
      run: pytest
